[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next/static"

[build.environment]
  NODE_VERSION = "20"
  SKIP_ENV_VALIDATION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
